AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'ramparts.gemspec'

ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - 'spec/data/**/*'

Layout/SpaceAfterComma:
  Exclude:
    - 'spec/data/**/*'

Style/WordArray:
  Exclude:
    - 'spec/data/**/*'

LineLength:
  Max: 120
  Exclude:
    - 'spec/data/**/*'

BlockLength:
  Exclude:
    - 'spec/**/*'

MethodLength:
  CountComments: false
  Max: 100